---
sidebar: sidebar 
permalink: launch-migration-advisor-evs-manual.html 
keywords: overview, concepts, features, use case, workloads, how Workload Factory works, migration, manual, specification, deploy, deployment, plan 
summary: Accedi a NetApp Workload Factory per accedere al centro di pianificazione VMware.  È possibile creare manualmente un piano di distribuzione per EVS. 
---
= Creare manualmente un piano di distribuzione per Amazon EVS
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Accedi a NetApp Workload Factory per accedere al centro di pianificazione VMware.  Da lì, puoi creare manualmente un piano di distribuzione o un piano di migrazione per Amazon EVS personalizzato in base alle tue esigenze.

Tieni presente che per accedere a Workload Factory è necessario disporre di un nome utente e di una password.  Se non hai accesso, crea un account ora.  Vedi le istruzioni https://docs.netapp.com/us-en/workload-setup-admin/quick-start.html["qui"] .



== Crea un piano di distribuzione specificando manualmente i requisiti ambientali

È possibile specificare manualmente i requisiti per le macchine virtuali in Amazon Elastic VMware Service e utilizzare i file system Amazon FSx for NetApp ONTAP personalizzati come datastore esterni.

.Requisiti
* È necessario disporre di un abbonamento ad Amazon Elastic VMware Service.


.Fasi
. Accedi a Workload Factory utilizzando uno dei https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["esperienze di console"^] .
. Facoltativamente, se si accede a Workload Factory dalla console di Workload Factory, dal riquadro dei carichi di lavoro VMware, selezionare *VMware Planning Center* e quindi *VMware Planning Center*.  Viene visualizzato il centro di pianificazione VMware.
. Seleziona *Crea manualmente il piano EVS*.
. Inserisci i requisiti per il tuo ambiente VM.
+
[NOTE]
====
Tieni presenti i seguenti requisiti e raccomandazioni sulle prestazioni per la migrazione delle VM:

** Per motivi di prestazioni, per l'inventario delle VM si consiglia una capacità di archiviazione minima di 10 TiB.
** Per i datastore di Amazon Elastic VMware Service è richiesta una velocità di elaborazione minima, a seconda del numero di IOPS specificato per questa distribuzione.
** A seconda della configurazione del file system FSx for ONTAP, è necessario un numero minimo di datastore esterni affinché l'ambiente Amazon Elastic VMware Service raggiunga prestazioni ottimali.


====
. Quando sei pronto, seleziona *Revisiona piano* per rivedere il piano di migrazione.
. Rivedere il piano. Espandi ciascuna sezione per visualizzare i dettagli del piano.
+
Per impostazione predefinita, Workload Factory salva il piano di migrazione nel centro di pianificazione.  È possibile deselezionare questa opzione nella parte superiore della pagina.

. Facoltativamente, quando sei soddisfatto del piano di migrazione, puoi scaricare i dettagli del piano come documento PDF selezionando *Esporta piano (PDF)*.
. Quando sei pronto per effettuare il provisioning del piano di distribuzione, seleziona *Provisioning*.


link:deploy-fsx-file-system-evs.html["Implementa il file system FSX per ONTAP consigliato per i carichi di lavoro VMware"].
