---
settings:
  name: VMware workloads
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  release_notes_autogen:
    release_notes_repo: workload-relnotes
  langs: it-it,us-en,de-de,es-es,fr-fr,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentazione sui carichi di lavoro VMware
    url: "/index.html"
  - title: Note di rilascio
    entries:
    - title: Novità
      url: "/whats-new.html"
  - title: Inizia subito
    entries:
    - title: Scopri di più su NetApp Workload Factory per VMware
      url: "/learn-about-vmware-workloads.html"
    - title: Avvio rapido per la migrazione ad Amazon EVS
      url: "/quick-start-evs.html"
    - title: Guida rapida per la migrazione ad Amazon EC2
      url: "/quick-start-native.html"
    - title: Avvio rapido per la migrazione a VMware Cloud su AWS
      url: "/quick-start.html"
    - title: Esplora il centro di pianificazione VMware
      url: "/explore-planning-center.html"
  - title: Utilizzare il centro di pianificazione VMware
    entries:
    - title: Carica i dati dell'inventario della VM
      url: "/upload-vm-inventory.html"
    - title: Migrazione ad Amazon Elastic VMware Service
      entries:
      - title: Esplora i risparmi
        url: "/calculate-evs-savings.html"
      - title: Creare manualmente un piano di distribuzione
        url: "/launch-migration-advisor-evs-manual.html"
      - title: Creare un piano di distribuzione utilizzando il Migration Advisor
        url: "/launch-migration-advisor-evs.html"
      - title: Implementa il file system FSX per ONTAP consigliato
        url: "/deploy-fsx-file-system-evs.html"
    - title: Migrazione ad Amazon EC2
      entries:
      - title: Creare un piano di distribuzione utilizzando il Migration Advisor
        url: "/launch-onboarding-advisor-native.html"
      - title: Implementa il file system FSX per ONTAP consigliato
        url: "/deploy-fsx-file-system-native.html"
    - title: Migrazione a VMware Cloud su AWS
      entries:
      - title: Creare un piano di distribuzione utilizzando il Migration Advisor
        url: "/launch-onboarding-advisor.html"
      - title: Implementa il file system FSX per ONTAP consigliato
        url: "/deploy-fsx-file-system.html"
      - title: Connetti FSX per ONTAP a VMware Cloud su AWS
        url: "/connect-sddc-to-fsx.html"
      - title: Migra i tuoi dati nella nuova infrastruttura
        url: "/migrate-data.html"
  - title: Conoscenza e supporto
    entries:
    - title: Registrati per ricevere assistenza
      url: "/support-registration.html"
    - title: Richiedi assistenza
      url: "/get-help.html"
  - title: Note legali
    url: "/legal-notices.html"
product-family:
  name: NetApp Workload Factory
  repo: workload-family
