= Miglioramenti al Migration ADVISOR di Amazon EC2
:allow-uri-read: 




=== Miglioramenti al Migration ADVISOR di Amazon EC2

Questa versione di NetApp Workload Factory per VMware presenta diversi miglioramenti all'esperienza di consulenza sulla migrazione:

* *Raccolta dati*: BlueXP Workload Factory per VMware supporta la possibilità di raccogliere dati per un periodo di tempo specifico quando si utilizza il consulente per la migrazione.
* *Selezione VM*: BlueXP Workload Factory per VMware ora supporta la selezione delle VM che si desidera includere nella distribuzione della migrazione.
* *Esperienza rapida e avanzata*: Quando si utilizza il Migration ADVISOR, è ora possibile scegliere un'esperienza di migrazione rapida, utilizzando RVtools o l'esperienza avanzata, che utilizza il data collector del Migration ADVISOR.


https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["Crea un piano di implementazione per Amazon EC2 utilizzando il Migration Advisor"]
